name: Scrape AniWatch Data

on:
  schedule:
    # Jalankan setiap 12 jam karena scraping katalog butuh waktu lama
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper script
        # Tambahkan timeout 30 menit karena prosesnya lama
        timeout-minutes: 30
        run: python scraper.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Tambahkan kedua file JSON
          git add anime_homepage.json anime_catalog.json
          git diff --staged --quiet || (git commit -m "Update anime data" && git push)
